quarkus:
  default-locale: en
  locales:
    - en
    - ja
  http:
    port: 3000
    test-port: 8081
  hibernate-validator:
    fail-fast: false
    method-validation:
      allow-overriding-parameter-constraints: true
      allow-parameter-constraints-on-parallel-methods: true
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    jdbc:
      url: jdbc:postgresql://localhost:5432/Application
  mailer:
    host: ${SMTP_HOST}
    port: 587
    start-tls: REQUIRED
    auth: true
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    from: ${SMTP_FROM}
    mock: false
  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false
  management:
    enabled: true
