quarkus:
  http:
    port: 3000
    test-port: 8081
  hibernate-validator:
    fail-fast: false
    method-validation:
      allow-overriding-parameter-constraints: true
      allow-parameter-constraints-on-parallel-methods: true
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Zaq12wsx}
    jdbc:
      url: jdbc:postgresql://${DB_URL:localhost:5432}/Application
  live-reload:
    instrumentation: true

  hibernate-orm:
    database:
      generation: validate
    log:
      sql: false
